### PR TITLE
Dabonnie/fix cpu measurement test

### LINKED ISSUE #83: LinuxCpuMeasurementTestFixture.TestManualMeasurement test failure
## Description
```
  61% tests passed, 7 tests failed out of 18
  
  Label Time Summary:
  copyright     =   0.62 sec*proc (1 test)
  cppcheck      =   0.90 sec*proc (1 test)
  cpplint       =   1.86 sec*proc (1 test)
  flake8        =   0.98 sec*proc (1 test)
  gtest         =   3.41 sec*proc (10 tests)
  lint_cmake    =   0.57 sec*proc (1 test)
  linter        =   7.42 sec*proc (8 tests)
  pep257        =   0.66 sec*proc (1 test)
  uncrustify    =   1.10 sec*proc (1 test)
  xmllint       =   0.75 sec*proc (1 test)
  
  Total Test time (real) =  10.84 sec
  
  The following tests FAILED:
  	  2 - test_metrics_message_publisher (Failed)
  	  3 - test_linux_cpu_measurement_node (Failed)
  	  4 - test_linux_memory_measurement_node (Failed)
  	  5 - test_linux_process_cpu_measurement_node (Failed)
  	  6 - test_linux_process_memory_measurement_node (Failed)
  	  8 - test_periodic_measurement_node (Failed)
  	  9 - test_composition (Failed)
```

ASAN:
```
  61% tests passed, 7 tests failed out of 18
  
  Label Time Summary:
  copyright     =   0.50 sec*proc (1 test)
  cppcheck      =   0.74 sec*proc (1 test)
  cpplint       =   1.52 sec*proc (1 test)
  flake8        =   0.93 sec*proc (1 test)
  gtest         =   2.66 sec*proc (10 tests)
  lint_cmake    =   0.47 sec*proc (1 test)
  linter        =   6.32 sec*proc (8 tests)
  pep257        =   0.54 sec*proc (1 test)
  uncrustify    =   0.89 sec*proc (1 test)
  xmllint       =   0.73 sec*proc (1 test)
  
  Total Test time (real) =   8.98 sec
  
  The following tests FAILED:
  	  2 - test_metrics_message_publisher (Failed)
  	  3 - test_linux_cpu_measurement_node (Failed)
  	  4 - test_linux_memory_measurement_node (Failed)
  	  5 - test_linux_process_cpu_measurement_node (Failed)
  	  6 - test_linux_process_memory_measurement_node (Failed)
  	  8 - test_periodic_measurement_node (Failed)
  	  9 - test_composition (Failed)
  Errors while running CTest
```

## System (please complete the following information)
 - OS: Ubuntu Bionic (GH Actions)
 - ROS2 Distro: master

### PR DESCRIPTION
**Pull request by dabonnie**
Closes #83 

Blocked by #101 

Uses the work in #100 in order to refactor Linux CPU measurement tests

Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

### CODE REVIEW

**Comment by dabonnie** [comment]
Marking as draft until sufficient test repeats are accomplished. Currently running via
```./test_linux_memory_measurement_node --gtest_repeat=-1 --gtest_break_on_failure```

**Comment by dabonnie** [comment]
>1200 repeated tests and no failures

File: system_metrics_collector/test/system_metrics_collector/test_constants.hpp [hunk 1]
```diff
@@ -27,23 +27,21 @@
 namespace test_constants
 {
 constexpr const std::chrono::milliseconds kMeasurePeriod{50};
-constexpr const std::chrono::milliseconds kPublishPeriod{80};
+constexpr const std::chrono::milliseconds kPublishPeriod_old{80};
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_constants.hpp]: Can you add a comment as to why this is still required?

File: system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp [hunk 2]
```diff
@@ -305,7 +305,7 @@ TEST_F(LinuxMemoryMeasurementTestFixture, TestPublishMessage)
   // check expected received message
   const auto received_message = test_receive_measurements->GetLastReceivedMessage();
 
-  EXPECT_EQ(kTestNodeName, received_message.measurement_source_name);
+  EXPECT_EQ(kTestMemoryNodeName, received_message.measurement_source_name);
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp]: `kTestMemoryNodeName` is a `char[]`, so this *may* compare pointers if `received_message` is a `char *`. I suggest doing something like:
```c++
EXPECT_EQ(std::string(kTestMetricName), received_message);
```
This is working right now because `received_message` is being resolved as an `std::string` and `std::string` supports comparing against `const char *`.

File: system_metrics_collector/test/system_metrics_collector/test_constants.hpp (hunk 1 above)
Comment (dabonnie) [reply system_metrics_collector/test/system_metrics_collector/test_constants.hpp]: Sure. It will be removed in #103

File: system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp [hunk 3]
```diff
@@ -320,43 +198,98 @@ TEST_F(LinuxCpuMeasurementTestFixture, TestPublishMetricsMessage)
...
+  test_measure_linux_cpu_->configure();
+  ASSERT_EQ(State::PRIMARY_STATE_INACTIVE, test_measure_linux_cpu_->get_current_state().id());
+  ASSERT_FALSE(test_measure_linux_cpu_->IsStarted());
+
+  // activate the node manually (lifecycle transition): this allows collection and data publication
+  test_measure_linux_cpu_->activate();
+  ASSERT_EQ(State::PRIMARY_STATE_ACTIVE, test_measure_linux_cpu_->get_current_state().id());
+  ASSERT_TRUE(test_measure_linux_cpu_->IsStarted());
+
+  //
```
Comment (prajakta-gokhale) [inline system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp]: Extra `//` for this comment throughout.

File: system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp [hunk 4]
```diff
@@ -305,10 +305,10 @@ TEST_F(LinuxMemoryMeasurementTestFixture, TestPublishMessage)
   // check expected received message
   const auto received_message = test_receive_measurements->GetLastReceivedMessage();
 
-  EXPECT_EQ(kTestNodeName, received_message.measurement_source_name);
-  EXPECT_EQ(kTestMetricName, received_message.metrics_source);
+  EXPECT_EQ(std::string(kTestMemoryNodeName), received_message.measurement_source_name);
```
Comment (prajakta-gokhale) [inline system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp]: Is `std::string()` needed? Seems like it wasn't before?

Comment (prajakta-gokhale) [reply system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp]: Oh I see it's so that comparison with _char[]_ works as expected. What was the original reason for making these _char[]_  initially?

Comment (dabonnie) [reply system_metrics_collector/test/system_metrics_collector/test_linux_memory_measurement.cpp]: See @zmichaels11 comments above.

File: system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp (hunk 3 above)
Comment (dabonnie) [reply system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp]: That was from the original test, didn't change it.
