### PR TITLE
Fix test subscriber failures

### LINKED ISSUE #124: Test Failure test_subscriber_topic_statistics
## Description

Test failure via the [PR CI](https://github.com/ros-tooling/system_metrics_collector/pull/122/checks?check_run_id=553521889) which is unrelated to the PR. These tests also failed in the low 100s when repeating them with gtest flags.

It appears this is an issue with timing behavior and signaling via futures should be used to signify events.

## Expected Behavior
The tests pass, repeatedly

## Actual Behavior
The tests fail.

## To Reproduce

Either run CI or 
1). checkout source
2). build source
3). run the tests with ./test_subscriber_topic_statistics --gtest_repeat=-1 --gtest_break_on_failure

## System (please complete the following information)
 - OS: Ubuntu Bionic
 - ROS2 Distro: master

### PR DESCRIPTION
**Pull request by dabonnie**
Closes #124. This refactors the topic statistics subscriber tests to use futures to signal successful events rather than waiting on timing conditions.

Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

### CODE REVIEW

**Comment by dabonnie** [comment]
Currently running ` ./test_subscriber_topic_statistics --gtest_repeat=-1 --gtest_break_on_failure` locally. Will provide results tomorrow (if positive, otherwise more fixes on the horizon).

**Comment by dabonnie** [comment]
Last test run:

```
Repeating all tests (iteration 2422) . . .

[==========] Running 7 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from SubscriberTopicStatisticsNodeTestFixture
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestStartAndStop
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestStartAndStop (12 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestSubscriptionCallback
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestSubscriptionCallback (1023 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestLifecycleManually_reactivate
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestLifecycleManually_reactivate (19 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestMetricsMessagePublisher
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestMetricsMessagePublisher (1032 ms)
[----------] 4 tests from SubscriberTopicStatisticsNodeTestFixture (2087 ms total)

[----------] 3 tests from RclcppFixture
[ RUN      ] RclcppFixture.TestConstructorNodeNameValidation
[       OK ] RclcppFixture.TestConstructorNodeNameValidation (0 ms)
[ RUN      ] RclcppFixture.TestConstructorPublishPeriodValidation
Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high.
2020-04-02 23:38:56.183 [RTPS Error] Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high. -> Function getUnicastPort
```

Running overnight with `export ROS_DOMAIN_ID=242; ./test_subscriber_topic_statistics --gtest_repeat=-1 --gtest_break_on_failure`

**Comment by dabonnie** [comment]
Last nights test run:

```
Repeating all tests (iteration 1141) . . .

[==========] Running 7 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from SubscriberTopicStatisticsNodeTestFixture
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestStartAndStop
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestStartAndStop (8 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestSubscriptionCallback
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestSubscriptionCallback (1010 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestLifecycleManually_reactivate
[       OK ] SubscriberTopicStatisticsNodeTestFixture.TestLifecycleManually_reactivate (17 ms)
[ RUN      ] SubscriberTopicStatisticsNodeTestFixture.TestMetricsMessagePublisher
Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high.
2020-04-03 01:40:47.067 [RTPS Error] Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high. -> Function getUnicastPort
```

So not sure how to work around the port issue, but the tests appear to be solid.

File: system_metrics_collector/test/system_metrics_collector/test_functions.hpp [hunk 1]
```diff
@@ -152,26 +152,41 @@ class PromiseSetter
 class MetricsMessageSubscriber : public rclcpp::Node, public PromiseSetter
 {
 public:
-  explicit MetricsMessageSubscriber(const std::string & name)
+  /**
+   *
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_functions.hpp:156]: missing doc?

File: system_metrics_collector/test/system_metrics_collector/test_functions.hpp [hunk 2]
```diff
@@ -152,26 +152,41 @@ class PromiseSetter
...
+   * @param name the node name
+   * @param name the topic name
+   * @param promise_trigger the PromiseSetter::SetPromise will be called when the number of messages
+   * received is >= the promise_trigger.
+   */
+  MetricsMessageSubscriber(const std::string & name, const std::string topic_name)
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_functions.hpp:162]: `topic_name` is passed by copy. Is this intentional?

File: system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp [hunk 3]
```diff
@@ -267,6 +268,7 @@ TEST_F(LinuxCpuMeasurementTestFixture, TestPublishMessage)
   //
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_linux_cpu_measurement.cpp:268]:
```suggestion
```

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp [hunk 4]
```diff
@@ -359,37 +381,53 @@ TEST_F(RclcppFixture, TestConstructorTopicNameValidation) {
...
+
+  // check the received message
+  const auto received_message = receive_messages->GetLastReceivedMessage();
+  for (const auto & stats_point : received_message.statistics) {
+    const auto type = stats_point.data_type;
+    switch (type) {
+      case StatisticDataType::STATISTICS_DATA_TYPE_SAMPLE_COUNT:
+        EXPECT_GT(dummy_publisher_->GetNumberPublished(), 1) << "unexpected sample count";
+        break;
+    }
```
Comment (zmichaels11) [inline system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:431]: Add a `default` case that does nothing with a comment on why it does nothing

File: system_metrics_collector/test/system_metrics_collector/test_functions.hpp (hunk 2 above)
Comment (dabonnie) [reply system_metrics_collector/test/system_metrics_collector/test_functions.hpp:162]: No, will fix.

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp [hunk 5]
```diff
@@ -110,20 +116,9 @@ class TestSubscriberTopicStatisticsNode
     return data;
   }
 
-  /**
-   * Spin a MetricsMessageSubscriber node until the desired MetricsMessages are received.
-   */
-  void SpinUntilMessageReceived()
+  std::vector<StatisticData> GetPublishedCollectorData() const
```
Comment (mm318) [inline system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: Return by const reference.

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp [hunk 6]
```diff
@@ -148,16 +146,28 @@ class DummyMessagePublisher : public rclcpp::Node
   : Node("dummy_publisher"), publisher_(nullptr)
   {
     publisher_ = create_publisher<DummyMessage>(kTestTopicName, 10);
+    publish_timer_ = this->create_wall_timer(
+      kImuPublishPeriod, [this]() {
```
Comment (mm318) [inline system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:150]: A `DummyMessage` publisher still uses an `Imu` publish period?

File: system_metrics_collector/test/system_metrics_collector/test_functions.hpp [hunk 7]
```diff
@@ -152,26 +152,43 @@ class PromiseSetter
...
-  MetricsMessage GetLastReceivedMessage()
+  MetricsMessage GetLastReceivedMessage() const
   {
     std::unique_lock<std::mutex> ulock{mutex_};
     return last_received_message_;
   }
 
+  /**
+   * Return the number of messages received
+   * @return
```
Comment (zmichaels11) [inline system_metrics_collector/test/system_metrics_collector/test_functions.hpp:185]: return what?

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp (hunk 5 above)
Comment (zmichaels11) [reply system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: the vector is built within the function

Comment (dabonnie) [reply system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: Why const reference? Won't reads and writes need to be guarded then? Why not just return a copy in order to read data?

Comment (zmichaels11) [reply system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: I think it depends on the intended use case. If the vector is only needed for short periods, then const ref would be preferred. I think the most flexible use would be to return by const ref and then explicitly assign to a non-reference if a copy is required.

Comment (mm318) [reply system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: That's up to the caller.

Even if `GetPublishedCollectorData()` returns by const reference, if the caller wants a copy, it can do:
```
std::vector<StatisticData> data = node->GetPublishedCollectorData();
```
And now if the caller otherwise wants to avoid a copy, do:
```
const std::vector<StatisticData> & data = node->GetPublishedCollectorData();
```

Comment (zmichaels11) [reply system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:119]: Nit:
```c++
auto data = node->GetPublishedCollectorData();
```
`auto` without the `&` will create a local copy.

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp [hunk 8]
```diff
@@ -272,31 +288,37 @@ TEST_F(SubscriberTopicStatisticsNodeTestFixture, TestStartAndStop) {
...
+  ex.add_node(test_topic_stats_node_->get_node_base_interface());
+  ex.add_node(dummy_publisher_);
+
+  // future fires for a single publish, otherwise long timeout
+  ex.spin_until_future_complete(test_topic_stats_node_->GetFuture(), kTestDuration);
 
-  test_topic_stats_node_->SpinUntilMessageReceived();
+  // check we have at least published once
+  EXPECT_EQ(test_topic_stats_node_->GetNumPublished(), 1);
+  // check that IMU data was actually published
```
Comment (mm318) [inline system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:308]: Comment still mentions "IMU data".

File: system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp [hunk 9]
```diff
@@ -359,37 +381,57 @@ TEST_F(RclcppFixture, TestConstructorTopicNameValidation) {
...
-    EXPECT_TRUE(std::isnan(data.standard_deviation));
+  test_node->activate();
+  EXPECT_EQ(State::PRIMARY_STATE_ACTIVE, test_node->get_current_state().id());
+
+  // wait until a metrics message was received
+  ex.spin_until_future_complete(
+    receive_messages->GetFuture(),
+    kTestDuration);
+
+  // check that IMU data was actually published
```
Comment (mm318) [inline system_metrics_collector/test/topic_statistics_collector/test_subscriber_topic_statistics.cpp:418]: Comment still mentions "IMU data".
